"""Added profit commission risk

Revision ID: ae77638c85e3
Revises: e3f9f99af195
Create Date: 2026-08-07 00:10:49.684530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae77638c85e3'
down_revision = 'e3f9f99af195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('risk')
        batch_op.drop_column('commission')
        batch_op.drop_column('profit_loss')

    # ### end Alembic commands ###
