"""Added screenshot fields

Revision ID: d08b238cdf3f
Revises: ae77638c85e3
Create Date: 2026-08-07 00:43:20.334737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08b238cdf3f'
down_revision = 'ae77638c85e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('after_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('after_image')
        batch_op.drop_column('before_image')

    # ### end Alembic commands ###
